fix: Permission error on Windows
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jnrg\\AppData\\Local\\Temp\\requirements_micropipenv-qb069zqt.txt'
```