Support Python versions with multiple digits
    AssertionError: Regex pattern 'Running Python version \\d.\\d, but Pipfile.lock requires Python version 5.9'
    does not match 'Running Python version 3.10, but Pipfile.lock requires Python version 5.9'.